// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Request
	Response
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Key   string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Err   string   `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Keys  []string `protobuf:"bytes,4,rep,name=keys" json:"keys,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Response) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *Response) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Response)(nil), "api.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kv service

type KvClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Keys(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Response, error)
	HasKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type kvClient struct {
	cc *grpc.ClientConn
}

func NewKvClient(cc *grpc.ClientConn) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/api.Kv/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/api.Kv/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/api.Kv/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Keys(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/api.Kv/Keys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) HasKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/api.Kv/HasKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kv service

type KvServer interface {
	Get(context.Context, *Request) (*Response, error)
	Put(context.Context, *Request) (*Response, error)
	Delete(context.Context, *Request) (*Response, error)
	Keys(context.Context, *google_protobuf.Empty) (*Response, error)
	HasKey(context.Context, *Request) (*Response, error)
}

func RegisterKvServer(s *grpc.Server, srv KvServer) {
	s.RegisterService(&_Kv_serviceDesc, srv)
}

func _Kv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kv/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Put(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kv/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kv/Keys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Keys(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_HasKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).HasKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Kv/HasKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).HasKey(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kv_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Kv_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kv_Delete_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _Kv_Keys_Handler,
		},
		{
			MethodName: "HasKey",
			Handler:    _Kv_HasKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x18, 0xc4, 0xdd, 0x66, 0xad, 0xee, 0x87, 0x82, 0x7c, 0x88, 0x2c, 0xf5, 0x52, 0x16, 0xc1, 0x9e,
	0xb2, 0xa8, 0xaf, 0xa0, 0x28, 0xec, 0x45, 0xf6, 0xe4, 0x75, 0x0b, 0x63, 0x29, 0x5d, 0x4d, 0xcc,
	0x9f, 0x42, 0x9e, 0xd3, 0x17, 0x92, 0x24, 0xf5, 0x26, 0xac, 0xb7, 0x99, 0xe1, 0x97, 0x49, 0x32,
	0x54, 0x0d, 0x7a, 0x2b, 0xb5, 0x51, 0x4e, 0xb1, 0x18, 0xf4, 0x76, 0x71, 0xbd, 0x51, 0x6a, 0x33,
	0xa2, 0x4d, 0xd1, 0xda, 0xbf, 0xb7, 0xf8, 0xd0, 0x2e, 0x64, 0xa2, 0xb9, 0xa3, 0x93, 0x1e, 0x5f,
	0x1e, 0xd6, 0xf1, 0x05, 0x89, 0x1d, 0x42, 0x5d, 0x2c, 0x8b, 0x55, 0xd5, 0x47, 0xc9, 0x97, 0x74,
	0xbc, 0x1f, 0x46, 0x8f, 0x7a, 0x96, 0xb2, 0x6c, 0x9a, 0x37, 0x3a, 0xed, 0x61, 0xb5, 0xfa, 0xb4,
	0xf8, 0xef, 0x99, 0xc8, 0xc1, 0x98, 0x5a, 0x64, 0x0e, 0xc6, 0x30, 0x53, 0xb9, 0x43, 0xb0, 0x75,
	0xb9, 0x14, 0xab, 0xaa, 0x4f, 0xfa, 0xfe, 0xbb, 0xa0, 0x59, 0xb7, 0xe7, 0x1b, 0x12, 0xcf, 0x70,
	0x7c, 0x26, 0xe3, 0x47, 0x0e, 0xaf, 0x5b, 0x9c, 0x1f, 0x5c, 0xbe, 0xb8, 0x39, 0x8a, 0xd4, 0xab,
	0x9f, 0xa4, 0x6e, 0x69, 0xfe, 0x88, 0x11, 0x0e, 0x53, 0x60, 0x4b, 0x65, 0x87, 0x60, 0xf9, 0x4a,
	0xe6, 0xb9, 0xe4, 0xef, 0x5c, 0xf2, 0x29, 0xce, 0xf5, 0x67, 0xf3, 0xcb, 0x60, 0x3b, 0x84, 0x89,
	0xe6, 0xf5, 0x3c, 0x35, 0x3d, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x70, 0x63, 0x30, 0x95, 0x98,
	0x01, 0x00, 0x00,
}
